plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true
include:
  - INDEX.md
  - LICENSE-CODE.md
  - LICENSE-DOC.md

remote_theme: "jekyll/minima@0b7ca6b"

title: Paul Marcelin's Musings
description: ""
author: ""

# defaults:
#   -
#     scope:
#       path: ""  # all files
#       # type: "posts"
#     values:
#       layout: "default"

timezone: America/Los_Angeles
encoding: utf-8
markdown: GFM
