plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true
include:
  - INDEX.md
  - LICENSE-CODE.md
  - LICENSE.md

pages:

remote_theme: "jekyll/minima@0b7ca6b"

minima:
  date_format: "%Y-%m-%d"
  skin: auto
  nav_pages:
  show_excerpts: true
  social_links:
  hide_site_feed_link: true

title: sqlxpert.github.io
description: >-
  Original source code: GPLv3; other original content: CC BY-NC-ND 4.0; non-original content: indicated license
author:
  name: Paul Marcelin
  email: marc\[DELETE\]elin@alumni.cmu.edu

defaults:
#   -
#     scope:
#       path: ""  # all files
#       # type: "posts"
#     values:
#       layout: "default"

timezone: America/Los_Angeles
encoding: utf-8
markdown: GFM
